/**
 * DADOS DEMONSTRATIVOS — tudo neste arquivo é fictício.
 *
 * Nomes, e-mails (domínio reservado example.com/.example), telefones, pedidos,
 * rastreios e conversas existem apenas para demonstrar a interface. Nenhum
 * dado foi obtido da Shopify, do WhatsApp, de e-mail ou de um modelo de IA.
 */
import { demoDate, demoTime } from "@/lib/format";
import type {
  AgentConfig,
  AuditEntry,
  Automation,
  Conversation,
  Customer,
  KnowledgeItem,
  Member,
  MessageTemplate,
  Order,
  QuickReply,
  Store,
  TagDefinition,
  Team,
} from "./types";

export const organization = {
  id: "org-horizonte",
  name: "Grupo Horizonte",
  plan: "Demonstração",
};

export const CURRENT_USER_ID = "u-marina";

export const stores: Store[] = [
  {
    id: "aurora",
    name: "Aurora Cosméticos",
    color: "#b4577a",
    orderPrefix: "AU",
    whatsappLabel: "WhatsApp Aurora",
    emailAddress: "atendimento@aurora.example",
  },
  {
    id: "lume",
    name: "Casa Lume",
    color: "#b27a26",
    orderPrefix: "CL",
    whatsappLabel: "WhatsApp Casa Lume",
    emailAddress: "contato@casalume.example",
  },
  {
    id: "trilha",
    name: "Trilha Outdoor",
    color: "#3d7a50",
    orderPrefix: "TO",
    whatsappLabel: "WhatsApp Trilha",
    emailAddress: "suporte@trilhaoutdoor.example",
  },
];

export const teams: Team[] = [
  {
    id: "t-revisao",
    name: "Revisão e exceções",
    description: "Recebe as conversas que o agente de IA encaminha para revisão humana.",
  },
  { id: "t-financeiro", name: "Financeiro", description: "Reembolsos, estornos, pagamentos e notas fiscais." },
  { id: "t-logistica", name: "Logística", description: "Trocas, devoluções, atrasos e contato com transportadoras." },
];

export const members: Member[] = [
  {
    id: "u-marina",
    name: "Marina Costa",
    email: "marina@horizonte.example",
    role: "proprietario",
    status: "ativo",
    teamIds: ["t-revisao"],
    storeIds: "all",
    lastSeenAt: demoTime("14:30"),
  },
  {
    id: "u-rafael",
    name: "Rafael Nunes",
    email: "rafael@horizonte.example",
    role: "supervisor",
    status: "ativo",
    teamIds: ["t-revisao"],
    storeIds: "all",
    lastSeenAt: demoTime("14:12"),
  },
  {
    id: "u-bianca",
    name: "Bianca Lopes",
    email: "bianca@horizonte.example",
    role: "atendente",
    status: "ativo",
    teamIds: ["t-revisao"],
    storeIds: ["aurora", "lume"],
    lastSeenAt: demoTime("13:47"),
  },
  {
    id: "u-thiago",
    name: "Thiago Mendes",
    email: "thiago@horizonte.example",
    role: "atendente",
    status: "ativo",
    teamIds: ["t-logistica"],
    storeIds: ["trilha"],
    lastSeenAt: demoTime("11:05"),
  },
  {
    id: "u-camila",
    name: "Camila Rocha",
    email: "camila@horizonte.example",
    role: "atendente",
    status: "ativo",
    teamIds: ["t-financeiro"],
    storeIds: "all",
    lastSeenAt: demoTime("17:40", -1),
  },
  {
    id: "u-joao",
    name: "João Pereira",
    email: "joao@horizonte.example",
    role: "atendente",
    status: "convite_pendente",
    teamIds: ["t-logistica"],
    storeIds: ["trilha"],
    invitedAt: demoTime("10:00", -2),
  },
  {
    id: "u-leticia",
    name: "Letícia Arantes",
    email: "leticia@horizonte.example",
    role: "supervisor",
    status: "convite_expirado",
    teamIds: [],
    storeIds: ["lume"],
    invitedAt: demoDate(2, 9, "09:00"),
  },
];

export const customers: Customer[] = [
  {
    id: "cu-01",
    name: "Juliana Ferreira",
    email: "juliana.ferreira@example.com",
    phone: "+55 11 95550-3021",
    storeId: "aurora",
    city: "São Paulo, SP",
    customerSince: demoDate(10, 11, "12:00", 2025),
    tags: ["recorrente"],
    notes: [],
    lastActivityAt: demoTime("14:21"),
  },
  {
    id: "cu-02",
    name: "Pedro Albuquerque",
    email: "pedro.alb@example.com",
    phone: "+55 41 95550-7788",
    storeId: "trilha",
    city: "Curitiba, PR",
    customerSince: demoDate(18, 9, "10:12"),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("13:11"),
  },
  {
    id: "cu-03",
    name: "Luiza Martins",
    email: "luiza.martins@example.com",
    phone: "+55 31 95550-1180",
    storeId: "aurora",
    city: "Belo Horizonte, MG",
    customerSince: demoDate(2, 3),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("14:27"),
  },
  {
    id: "cu-04",
    name: "Marcos Vinícius Silva",
    email: "marcos.vs@example.com",
    phone: "+55 11 95550-2245",
    storeId: "lume",
    city: "Campinas, SP",
    customerSince: demoDate(22, 9),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("11:02"),
  },
  {
    id: "cu-05",
    name: "Fernanda Dias",
    email: "fernanda.d@example.com",
    phone: "",
    storeId: "aurora",
    city: "Não informado",
    customerSince: demoTime("12:40"),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("12:41"),
  },
  {
    id: "cu-06",
    name: "Ricardo Gomes",
    email: "ricardo.gomes@example.com",
    phone: "+55 48 95550-6612",
    storeId: "trilha",
    city: "Florianópolis, SC",
    customerSince: demoDate(14, 9),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("10:50"),
  },
  {
    id: "cu-07",
    name: "Aline Souza",
    email: "aline.souza@example.com",
    phone: "+55 21 95550-4410",
    storeId: "lume",
    city: "Rio de Janeiro, RJ",
    customerSince: demoDate(10, 9),
    tags: ["pj"],
    notes: [],
    lastActivityAt: demoTime("09:30"),
  },
  {
    id: "cu-08",
    name: "Bruno Carvalho",
    email: "bruno.carvalho@example.com",
    phone: "+55 71 95550-9033",
    storeId: "aurora",
    city: "Salvador, BA",
    customerSince: demoDate(9, 9),
    tags: [],
    notes: [
      {
        id: "n-cu08-1",
        authorId: "u-bianca",
        at: demoDate(18, 9, "15:20"),
        body: "Cliente já perguntou do atraso em 12/09 e 18/09. Abri chamado com a transportadora em 18/09.",
      },
    ],
    lastActivityAt: demoTime("12:06"),
  },
  {
    id: "cu-09",
    name: "Carla Menezes",
    email: "carla.m@example.com",
    phone: "+55 81 95550-3377",
    storeId: "lume",
    city: "Recife, PE",
    customerSince: demoDate(28, 8),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("09:20"),
  },
  {
    id: "cu-10",
    name: "Gustavo Lima",
    email: "gustavo.lima@example.com",
    phone: "+55 62 95550-8120",
    storeId: "aurora",
    city: "Goiânia, GO",
    customerSince: demoDate(20, 9),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("08:40"),
  },
  {
    id: "cu-11",
    name: "Patrícia Ramos",
    email: "patricia.ramos@example.com",
    phone: "+55 31 95550-5560",
    storeId: "aurora",
    city: "Belo Horizonte, MG",
    customerSince: demoDate(24, 9),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("14:05"),
  },
  {
    id: "cu-12",
    name: "Rodrigo Teixeira",
    email: "rodrigo.t@example.com",
    phone: "+55 11 95550-7001",
    storeId: "lume",
    city: "São Paulo, SP",
    customerSince: demoTime("11:20"),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("11:40"),
  },
  {
    id: "cu-13",
    name: "Mariana Castro",
    email: "mariana.castro@example.com",
    phone: "+55 85 95550-2290",
    storeId: "aurora",
    city: "Fortaleza, CE",
    customerSince: demoDate(20, 7),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("14:26"),
  },
  {
    id: "cu-14",
    name: "Eduardo Moreira",
    email: "eduardo.moreira@example.com",
    phone: "+55 51 95550-4876",
    storeId: "trilha",
    city: "Porto Alegre, RS",
    customerSince: demoDate(16, 9),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("13:16"),
  },
  {
    id: "cu-15",
    name: "Sofia Almeida",
    email: "sofia.almeida@example.com",
    phone: "+55 13 95550-3133",
    storeId: "lume",
    city: "Santos, SP",
    customerSince: demoDate(23, 9),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("16:45", -1),
  },
  {
    id: "cu-16",
    name: "Helena Prado",
    email: "helena.prado@example.com",
    phone: "+55 92 95550-6021",
    storeId: "lume",
    city: "Manaus, AM",
    customerSince: demoTime("14:20"),
    tags: [],
    notes: [],
    lastActivityAt: demoTime("14:29"),
  },
  {
    id: "cu-17",
    name: "Vitor Hugo Andrade",
    email: "vitor.andrade@example.com",
    phone: "+55 41 95550-1911",
    storeId: "trilha",
    city: "Curitiba, PR",
    customerSince: demoDate(12, 6, "12:00", 2025),
    tags: ["vip"],
    notes: [
      {
        id: "n-cu17-1",
        authorId: "u-thiago",
        at: demoDate(30, 8, "10:00"),
        body: "Faz trilhas longas; costuma pedir indicação de equipamento antes de comprar.",
      },
    ],
    lastActivityAt: demoDate(30, 8, "18:22"),
  },
  {
    id: "cu-18",
    name: "Renata Figueiredo",
    email: "renata.fig@example.com",
    phone: "+55 11 95550-8844",
    storeId: "aurora",
    city: "São Paulo, SP",
    customerSince: demoDate(18, 5, "12:00", 2025),
    tags: ["vip", "recorrente"],
    notes: [],
    lastActivityAt: demoDate(3, 9, "21:05"),
  },
];

const CARRIER = "Transportadora Exemplo";

export const orders: Order[] = [
  {
    id: "AU1042",
    number: "#AU1042",
    storeId: "aurora",
    customerId: "cu-01",
    createdAt: demoDate(21, 9, "16:20"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 4821",
    items: [
      { title: "Sérum Vitamina C", variant: "30 ml", sku: "AU-VC-30", quantity: 1, unitPrice: 89.9 },
      { title: "Protetor Solar Facial FPS 50", variant: "50 g", sku: "AU-PS-50", quantity: 1, unitPrice: 64.9 },
    ],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Alvorada, 2•• — ap. 1•", city: "São Paulo, SP", zip: "04•••-020" },
    tracking: {
      carrier: CARRIER,
      code: "TX5820193BR",
      estimatedDelivery: demoDate(25, 9),
      events: [
        { at: demoDate(22, 9, "15:02"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(23, 9, "07:40"), description: "Em trânsito para a unidade de distribuição", location: "São Paulo, SP" },
        { at: demoTime("08:10"), description: "Saiu para entrega", location: "São Paulo, SP" },
        { at: demoTime("10:41"), description: "Entregue ao destinatário", location: "São Paulo, SP" },
      ],
    },
  },
  {
    id: "AU0987",
    number: "#AU0987",
    storeId: "aurora",
    customerId: "cu-01",
    createdAt: demoDate(2, 8, "20:14"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Pix",
    items: [{ title: "Hidratante Facial Aurora", variant: "50 g", sku: "AU-HF-50", quantity: 1, unitPrice: 72 }],
    shipping: 18.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Alvorada, 2•• — ap. 1•", city: "São Paulo, SP", zip: "04•••-020" },
    tracking: {
      carrier: CARRIER,
      code: "TX4410552BR",
      estimatedDelivery: demoDate(7, 8),
      events: [
        { at: demoDate(3, 8, "14:00"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(6, 8, "13:12"), description: "Entregue ao destinatário", location: "São Paulo, SP" },
      ],
    },
  },
  {
    id: "TO5531",
    number: "#TO5531",
    storeId: "trilha",
    customerId: "cu-02",
    createdAt: demoDate(18, 9, "10:12"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "em_transito",
    paymentMethod: "Pix",
    items: [
      { title: "Barraca Serra 2P", variant: "Verde musgo", sku: "TO-BS2-VM", quantity: 1, unitPrice: 689 },
      { title: "Isolante térmico", variant: "Único", sku: "TO-IT-01", quantity: 1, unitPrice: 79.9 },
    ],
    shipping: 34.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Carlos de Carvalho, 1•• — casa", city: "Curitiba, PR", zip: "80•••-130" },
    tracking: {
      carrier: CARRIER,
      code: "TX7731940BR",
      estimatedDelivery: demoDate(30, 9),
      events: [
        { at: demoDate(24, 9, "16:25"), description: "Objeto postado", location: "Joinville, SC" },
        { at: demoTime("06:50"), description: "Em trânsito para a unidade de distribuição", location: "Curitiba, PR" },
      ],
    },
  },
  {
    id: "AU1031",
    number: "#AU1031",
    storeId: "aurora",
    customerId: "cu-03",
    createdAt: demoDate(15, 9, "09:48"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 1077",
    items: [
      { title: "Sérum Vitamina C", variant: "30 ml", sku: "AU-VC-30", quantity: 1, unitPrice: 89.9 },
      { title: "Ácido Glicólico 8%", variant: "30 ml", sku: "AU-AG-30", quantity: 1, unitPrice: 69.9 },
    ],
    shipping: 0,
    discount: 16,
    refunded: 0,
    address: { line: "Av. do Contorno, 5•• — ap. 7•", city: "Belo Horizonte, MG", zip: "30•••-110" },
    tracking: {
      carrier: CARRIER,
      code: "TX6120038BR",
      estimatedDelivery: demoDate(20, 9),
      events: [
        { at: demoDate(16, 9, "11:30"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(19, 9, "15:05"), description: "Entregue ao destinatário", location: "Belo Horizonte, MG" },
      ],
    },
  },
  {
    id: "CL2210",
    number: "#CL2210",
    storeId: "lume",
    customerId: "cu-04",
    createdAt: demoDate(22, 9, "19:31"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "em_transito",
    paymentMethod: "Cartão de crédito •••• 3390",
    items: [{ title: "Luminária Arco Pérola", variant: "Bivolt", sku: "CL-LAP-BV", quantity: 1, unitPrice: 459 }],
    shipping: 29.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Barão de Jaguara, 9•• — casa 2", city: "Campinas, SP", zip: "13•••-001" },
    tracking: {
      carrier: CARRIER,
      code: "TX8823016BR",
      estimatedDelivery: demoDate(29, 9),
      events: [{ at: demoDate(24, 9, "09:15"), description: "Saiu do centro de distribuição", location: "Cajamar, SP" }],
    },
  },
  {
    id: "TO5498",
    number: "#TO5498",
    storeId: "trilha",
    customerId: "cu-06",
    createdAt: demoDate(14, 9, "21:03"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 6604",
    items: [{ title: "Bota Cânion", variant: "Tamanho 42", sku: "TO-BC-42", quantity: 1, unitPrice: 399 }],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Bocaiúva, 1•• — ap. 3••", city: "Florianópolis, SC", zip: "88•••-000" },
    tracking: {
      carrier: CARRIER,
      code: "TX3305871BR",
      estimatedDelivery: demoDate(21, 9),
      events: [
        { at: demoDate(16, 9, "10:00"), description: "Objeto postado", location: "Joinville, SC" },
        { at: demoDate(20, 9, "14:22"), description: "Entregue ao destinatário", location: "Florianópolis, SC" },
      ],
    },
  },
  {
    id: "CL2187",
    number: "#CL2187",
    storeId: "lume",
    customerId: "cu-07",
    createdAt: demoDate(10, 9, "14:40"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Boleto",
    items: [
      { title: "Jogo de Cama Linho", variant: "Queen · Areia", sku: "CL-JCL-QA", quantity: 1, unitPrice: 349 },
      { title: "Manta Tricô", variant: "Off-white", sku: "CL-MT-OW", quantity: 1, unitPrice: 189 },
    ],
    shipping: 24.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Voluntários da Pátria, 3•• — sala 4••", city: "Rio de Janeiro, RJ", zip: "22•••-000" },
    tracking: {
      carrier: CARRIER,
      code: "TX2091174BR",
      estimatedDelivery: demoDate(17, 9),
      events: [
        { at: demoDate(12, 9, "09:10"), description: "Objeto postado", location: "Cajamar, SP" },
        { at: demoDate(16, 9, "11:48"), description: "Entregue ao destinatário", location: "Rio de Janeiro, RJ" },
      ],
    },
  },
  {
    id: "AU1019",
    number: "#AU1019",
    storeId: "aurora",
    customerId: "cu-08",
    createdAt: demoDate(9, 9, "22:10"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "em_transito",
    paymentMethod: "Cartão de crédito •••• 2215",
    items: [{ title: "Kit Rotina Completa", variant: "Pele mista", sku: "AU-KRC-PM", quantity: 1, unitPrice: 289 }],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Chile, 4•• — ap. 2•", city: "Salvador, BA", zip: "40•••-060" },
    tracking: {
      carrier: CARRIER,
      code: "TX9014427BR",
      estimatedDelivery: demoDate(19, 9),
      events: [
        { at: demoDate(12, 9, "10:40"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(13, 9, "19:02"), description: "Em trânsito", location: "São Paulo, SP" },
        { at: demoDate(16, 9, "08:31"), description: "Em trânsito para a unidade de distribuição", location: "Feira de Santana, BA" },
      ],
    },
  },
  {
    id: "CL2150",
    number: "#CL2150",
    storeId: "lume",
    customerId: "cu-09",
    createdAt: demoDate(28, 8, "11:05"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Pix",
    items: [{ title: "Difusor Brisa", variant: "Alecrim", sku: "CL-DB-AL", quantity: 1, unitPrice: 129 }],
    shipping: 19.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua da Aurora, 7•• — ap. 1••", city: "Recife, PE", zip: "50•••-000" },
    tracking: {
      carrier: CARRIER,
      code: "TX1187730BR",
      estimatedDelivery: demoDate(5, 9),
      events: [
        { at: demoDate(29, 8, "15:00"), description: "Objeto postado", location: "Cajamar, SP" },
        { at: demoDate(4, 9, "10:20"), description: "Entregue ao destinatário", location: "Recife, PE" },
      ],
    },
  },
  {
    id: "AU1050",
    number: "#AU1050",
    storeId: "aurora",
    customerId: "cu-10",
    createdAt: demoDate(20, 9, "13:30"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "em_transito",
    paymentMethod: "Cartão de crédito •••• 9012",
    items: [{ title: "Perfume Aurora Noite", variant: "50 ml", sku: "AU-PAN-50", quantity: 1, unitPrice: 219 }],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Av. T-63, 1•• — qd. 1•", city: "Goiânia, GO", zip: "74•••-100" },
    tracking: {
      carrier: CARRIER,
      code: "TX5539028BR",
      estimatedDelivery: demoDate(27, 9),
      events: [
        { at: demoDate(23, 9, "10:12"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(24, 9, "22:40"), description: "Em trânsito", location: "Brasília, DF" },
      ],
    },
  },
  {
    id: "AU1057",
    number: "#AU1057",
    storeId: "aurora",
    customerId: "cu-11",
    createdAt: demoDate(24, 9, "18:02"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "nao_enviado",
    paymentMethod: "Pix",
    items: [{ title: "Kit Presente Vitamina C", variant: "Único", sku: "AU-KPV-01", quantity: 1, unitPrice: 179 }],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Pernambuco, 6•• — ap. 5••", city: "Belo Horizonte, MG", zip: "30•••-150" },
  },
  {
    id: "CL2231",
    number: "#CL2231",
    storeId: "lume",
    customerId: "cu-12",
    createdAt: demoTime("11:20"),
    status: "aberto",
    financialStatus: "pendente",
    fulfillmentStatus: "nao_enviado",
    paymentMethod: "Pix",
    items: [{ title: "Cadeira Tucum", variant: "Natural", sku: "CL-CT-NA", quantity: 1, unitPrice: 899 }],
    shipping: 49.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Harmonia, 2•• — casa", city: "São Paulo, SP", zip: "05•••-010" },
  },
  {
    id: "AU0950",
    number: "#AU0950",
    storeId: "aurora",
    customerId: "cu-13",
    createdAt: demoDate(20, 7, "10:45"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 5530",
    items: [{ title: "Máscara Capilar Nutrição", variant: "250 g", sku: "AU-MCN-250", quantity: 1, unitPrice: 59.9 }],
    shipping: 18.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Tibúrcio Cavalcante, 1•• — ap. 8••", city: "Fortaleza, CE", zip: "60•••-120" },
    tracking: {
      carrier: CARRIER,
      code: "TX3372901BR",
      estimatedDelivery: demoDate(29, 7),
      events: [
        { at: demoDate(21, 7, "14:00"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(28, 7, "12:10"), description: "Entregue ao destinatário", location: "Fortaleza, CE" },
      ],
    },
  },
  {
    id: "TO5512",
    number: "#TO5512",
    storeId: "trilha",
    customerId: "cu-14",
    createdAt: demoDate(16, 9, "08:22"),
    status: "aberto",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 7781",
    items: [{ title: "Mochila Cume 40 L", variant: "Grafite", sku: "TO-MC40-GR", quantity: 1, unitPrice: 459 }],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Padre Chagas, 3•• — ap. 2••", city: "Porto Alegre, RS", zip: "90•••-160" },
    tracking: {
      carrier: CARRIER,
      code: "TX4478215BR",
      estimatedDelivery: demoDate(23, 9),
      events: [
        { at: demoDate(17, 9, "16:40"), description: "Objeto postado", location: "Joinville, SC" },
        { at: demoDate(22, 9, "10:05"), description: "Entregue ao destinatário", location: "Porto Alegre, RS" },
      ],
    },
  },
  {
    id: "CL2224",
    number: "#CL2224",
    storeId: "lume",
    customerId: "cu-15",
    createdAt: demoDate(23, 9, "22:48"),
    status: "cancelado",
    financialStatus: "reembolsado",
    fulfillmentStatus: "cancelado",
    paymentMethod: "Cartão de crédito •••• 4410",
    items: [{ title: "Espelho Oval Latão", variant: "60 × 90 cm", sku: "CL-EOL-6090", quantity: 1, unitPrice: 629 }],
    shipping: 0,
    discount: 0,
    refunded: 629,
    address: { line: "Av. Ana Costa, 4•• — ap. 1••", city: "Santos, SP", zip: "11•••-003" },
  },
  {
    id: "TO5450",
    number: "#TO5450",
    storeId: "trilha",
    customerId: "cu-17",
    createdAt: demoDate(30, 8, "18:22"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 0038",
    items: [
      { title: "Jaqueta Corta-vento", variant: "M · Azul", sku: "TO-JCV-MA", quantity: 1, unitPrice: 349 },
      { title: "Garrafa Térmica 750 ml", variant: "Aço", sku: "TO-GT-750", quantity: 1, unitPrice: 129 },
    ],
    shipping: 0,
    discount: 47.8,
    refunded: 0,
    address: { line: "Rua Mateus Leme, 2•• — casa", city: "Curitiba, PR", zip: "80•••-010" },
    tracking: {
      carrier: CARRIER,
      code: "TX2250719BR",
      estimatedDelivery: demoDate(3, 9),
      events: [
        { at: demoDate(31, 8, "15:30"), description: "Objeto postado", location: "Joinville, SC" },
        { at: demoDate(2, 9, "11:40"), description: "Entregue ao destinatário", location: "Curitiba, PR" },
      ],
    },
  },
  {
    id: "TO5301",
    number: "#TO5301",
    storeId: "trilha",
    customerId: "cu-17",
    createdAt: demoDate(12, 6, "09:10"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Pix",
    items: [{ title: "Barraca Serra 3P", variant: "Areia", sku: "TO-BS3-AR", quantity: 1, unitPrice: 899 }],
    shipping: 0,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Mateus Leme, 2•• — casa", city: "Curitiba, PR", zip: "80•••-010" },
    tracking: {
      carrier: CARRIER,
      code: "TX1009382BR",
      estimatedDelivery: demoDate(17, 6),
      events: [
        { at: demoDate(13, 6, "10:00"), description: "Objeto postado", location: "Joinville, SC" },
        { at: demoDate(16, 6, "16:12"), description: "Entregue ao destinatário", location: "Curitiba, PR" },
      ],
    },
  },
  {
    id: "AU1003",
    number: "#AU1003",
    storeId: "aurora",
    customerId: "cu-18",
    createdAt: demoDate(3, 9, "21:05"),
    status: "arquivado",
    financialStatus: "parcialmente_reembolsado",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 8120",
    items: [
      { title: "Kit Rotina Completa", variant: "Pele seca", sku: "AU-KRC-PS", quantity: 1, unitPrice: 289 },
      { title: "Tônico Calmante", variant: "120 ml", sku: "AU-TC-120", quantity: 1, unitPrice: 49.9 },
    ],
    shipping: 0,
    discount: 0,
    refunded: 49.9,
    address: { line: "Rua Oscar Freire, 1•• — ap. 9•", city: "São Paulo, SP", zip: "01•••-000" },
    tracking: {
      carrier: CARRIER,
      code: "TX6640187BR",
      estimatedDelivery: demoDate(8, 9),
      events: [
        { at: demoDate(4, 9, "13:00"), description: "Objeto postado", location: "Barueri, SP" },
        { at: demoDate(6, 9, "10:48"), description: "Entregue ao destinatário", location: "São Paulo, SP" },
      ],
    },
  },
  {
    id: "AU0921",
    number: "#AU0921",
    storeId: "aurora",
    customerId: "cu-18",
    createdAt: demoDate(5, 7, "19:40"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Cartão de crédito •••• 8120",
    items: [{ title: "Sérum Vitamina C", variant: "30 ml", sku: "AU-VC-30", quantity: 2, unitPrice: 89.9 }],
    shipping: 0,
    discount: 17.98,
    refunded: 0,
    address: { line: "Rua Oscar Freire, 1•• — ap. 9•", city: "São Paulo, SP", zip: "01•••-000" },
  },
  {
    id: "AU0870",
    number: "#AU0870",
    storeId: "aurora",
    customerId: "cu-18",
    createdAt: demoDate(18, 5, "08:55"),
    status: "arquivado",
    financialStatus: "pago",
    fulfillmentStatus: "entregue",
    paymentMethod: "Pix",
    items: [{ title: "Protetor Solar Facial FPS 50", variant: "50 g", sku: "AU-PS-50", quantity: 1, unitPrice: 64.9 }],
    shipping: 18.9,
    discount: 0,
    refunded: 0,
    address: { line: "Rua Oscar Freire, 1•• — ap. 9•", city: "São Paulo, SP", zip: "01•••-000" },
  },
];

const src = {
  order: (id: string, detail: string) => ({ kind: "order" as const, refId: id, label: `Pedido #${id}`, detail }),
  kb: (id: string, label: string, detail: string) => ({ kind: "knowledge" as const, refId: id, label, detail }),
  rule: (label: string, detail: string) => ({ kind: "rule" as const, label, detail }),
  product: (label: string, detail: string) => ({ kind: "product" as const, label, detail }),
};

export const conversations: Conversation[] = [
  {
    id: "cv-01",
    ticketNumber: 4812,
    customerId: "cu-01",
    storeId: "aurora",
    channel: "whatsapp",
    subject: "Sérum chegou quebrado — pedido #AU1042",
    reason: "reembolso",
    priority: "alta",
    state: "needs_review",
    assigneeId: null,
    teamId: "t-revisao",
    tags: ["reembolso", "produto-danificado"],
    unreadCount: 1,
    createdAt: demoTime("13:52"),
    lastActivityAt: demoTime("14:21"),
    slaDueAt: demoTime("14:48"),
    slaPaused: false,
    handoff: {
      reason: "Cliente pediu reembolso de item que chegou danificado.",
      rule: "Reembolsos sempre são transferidos para revisão humana.",
      at: demoTime("13:58"),
    },
    aiSummary:
      "O Sérum Vitamina C 30 ml do pedido #AU1042 (entregue hoje às 10:41) chegou com o frasco quebrado. A cliente enviou foto e pede reembolso do item; não quer reenvio.",
    aiSuggestion:
      "Pela política de trocas, produto danificado na entrega dá direito a reembolso do item (R$ 89,90). A decisão e o estorno dependem de validação da equipe.",
    orderIds: ["AU1042"],
    timeline: [
      {
        id: "m-0101",
        type: "message",
        author: "customer",
        at: demoTime("13:52"),
        body: "Oi, recebi meu pedido hoje, mas o frasco do sérum veio quebrado.",
        attachments: [{ name: "foto-frasco.jpg", kind: "image", size: "1,8 MB" }],
      },
      {
        id: "e-0102",
        type: "event",
        kind: "classified",
        at: demoTime("13:52"),
        text: "IA classificou o contato",
        detail: "Motivo: produto danificado · Prioridade: alta · Tag: produto-danificado",
      },
      {
        id: "e-0103",
        type: "event",
        kind: "lookup",
        at: demoTime("13:52"),
        text: "IA consultou o pedido #AU1042",
        detail: "Pago · Entregue hoje às 10:41 · 2 itens",
      },
      {
        id: "m-0104",
        type: "message",
        author: "ai",
        at: demoTime("13:53"),
        body: "Oi, Juliana! Sinto muito pelo frasco quebrado. Localizei seu pedido #AU1042, entregue hoje às 10:41. Para registrar a ocorrência, você pode confirmar se o problema foi só com o Sérum Vitamina C 30 ml?",
        delivery: "lida",
        sources: [
          src.order("AU1042", "Status de entrega e itens do pedido"),
          src.kb("kb-01", "Política de trocas e devoluções", "Seção “Produto danificado na entrega”, versão 3"),
        ],
      },
      {
        id: "m-0105",
        type: "message",
        author: "customer",
        at: demoTime("13:57"),
        body: "Sim, só ele. Quero o reembolso, não quero outro.",
      },
      {
        id: "e-0106",
        type: "event",
        kind: "classified",
        at: demoTime("13:57"),
        text: "IA atualizou o motivo do contato",
        detail: "Produto danificado → Reembolso · Tag adicionada: reembolso",
      },
      {
        id: "m-0107",
        type: "message",
        author: "ai",
        at: demoTime("13:58"),
        body: "Entendi. Pedidos de reembolso são aprovados pela nossa equipe. Já encaminhei seu caso com a foto e os dados do pedido, e você recebe o retorno por aqui. Posso ajudar com mais alguma coisa enquanto isso?",
        delivery: "lida",
        sources: [src.kb("kb-01", "Política de trocas e devoluções", "Seção “Reembolsos”, versão 3")],
      },
      {
        id: "e-0108",
        type: "event",
        kind: "handoff",
        at: demoTime("13:58"),
        text: "IA encaminhou para revisão humana",
        detail: "Reembolsos sempre são transferidos para revisão humana.",
      },
      { id: "m-0109", type: "message", author: "customer", at: demoTime("14:21"), body: "Ok, fico aguardando." },
    ],
  },
  {
    id: "cv-02",
    ticketNumber: 4809,
    customerId: "cu-02",
    storeId: "trilha",
    channel: "email",
    subject: "Prazo de entrega da barraca",
    reason: "prazo_entrega",
    priority: "normal",
    state: "needs_review",
    assigneeId: null,
    teamId: "t-revisao",
    tags: ["rastreio"],
    unreadCount: 1,
    createdAt: demoTime("13:10"),
    lastActivityAt: demoTime("13:11"),
    slaDueAt: demoTime("15:10"),
    slaPaused: false,
    handoff: {
      reason: "Resposta preparada pela IA aguardando aprovação.",
      rule: "E-mail da Trilha Outdoor está em modo copiloto.",
      at: demoTime("13:11"),
    },
    aiSummary:
      "O cliente quer saber se a Barraca Serra 2P (pedido #TO5531) chega antes de 03/10. O pedido foi postado em 24/09, com previsão de entrega em 30/09.",
    aiDraft: {
      body: "Olá, Pedro! Obrigado por escrever.\n\nSeu pedido #TO5531 foi postado em 24/09 e o código de rastreio é TX7731940BR. A previsão informada pela transportadora é de entrega até 30/09, antes da sua viagem.\n\nSe houver qualquer mudança na rota, você recebe um aviso por e-mail. Qualquer dúvida, é só responder esta mensagem.\n\nLia, da Trilha Outdoor",
      sources: [
        src.order("TO5531", "Postagem, código de rastreio e previsão de entrega"),
        src.kb("kb-02", "Prazos de entrega por região", "Região Sul, versão 2"),
      ],
      createdAt: demoTime("13:11"),
    },
    orderIds: ["TO5531"],
    timeline: [
      {
        id: "m-0201",
        type: "message",
        author: "customer",
        at: demoTime("13:10"),
        body: "Olá, comprei a Barraca Serra 2P no dia 18 e ainda não recebi o código de rastreio. Vou acampar no dia 3/10. Chega a tempo?\n\nPedro",
      },
      {
        id: "e-0202",
        type: "event",
        kind: "classified",
        at: demoTime("13:10"),
        text: "IA classificou o contato",
        detail: "Motivo: prazo de entrega · Prioridade: normal",
      },
      {
        id: "e-0203",
        type: "event",
        kind: "lookup",
        at: demoTime("13:10"),
        text: "IA consultou o pedido #TO5531",
        detail: "Pago · Em trânsito · Previsão 30/09",
      },
      {
        id: "e-0204",
        type: "event",
        kind: "draft",
        at: demoTime("13:11"),
        text: "IA preparou uma resposta para aprovação",
        detail: "Modo copiloto: nada é enviado sem aprovação de uma pessoa.",
      },
    ],
  },
  {
    id: "cv-03",
    ticketNumber: 4817,
    customerId: "cu-03",
    storeId: "aurora",
    channel: "whatsapp",
    subject: "Uso de Vitamina C com ácido glicólico",
    reason: "duvida_produto",
    priority: "normal",
    state: "ai_active",
    assigneeId: null,
    tags: [],
    unreadCount: 0,
    createdAt: demoTime("14:24"),
    lastActivityAt: demoTime("14:27"),
    slaDueAt: demoTime("14:57"),
    slaPaused: false,
    aiSummary:
      "Dúvida sobre combinar Sérum Vitamina C e Ácido Glicólico. A IA explicou a rotina recomendada e a cliente pediu o guia completo.",
    orderIds: ["AU1031"],
    timeline: [
      {
        id: "m-0301",
        type: "message",
        author: "customer",
        at: demoTime("14:24"),
        body: "Oi! Posso usar o sérum de vitamina C junto com o ácido glicólico?",
      },
      {
        id: "e-0302",
        type: "event",
        kind: "classified",
        at: demoTime("14:24"),
        text: "IA classificou o contato",
        detail: "Motivo: dúvida sobre produto · Prioridade: normal",
      },
      {
        id: "m-0303",
        type: "message",
        author: "ai",
        at: demoTime("14:24"),
        body: "Oi, Luiza! Pelo guia de uso da Aurora, o ideal é não aplicar os dois na mesma rotina: use a Vitamina C pela manhã e o ácido glicólico à noite, sempre com protetor solar durante o dia. Quer que eu envie o guia completo?",
        delivery: "lida",
        sources: [src.kb("kb-03", "Guia de uso: Linha Vitamina C", "Seção “Combinações”, versão 1")],
      },
      { id: "m-0304", type: "message", author: "customer", at: demoTime("14:27"), body: "Quero sim, pode mandar" },
    ],
  },
  {
    id: "cv-04",
    ticketNumber: 4805,
    customerId: "cu-04",
    storeId: "lume",
    channel: "whatsapp",
    subject: "Onde está o pedido #CL2210",
    reason: "rastreamento",
    priority: "normal",
    state: "awaiting_customer",
    assigneeId: null,
    tags: ["rastreio"],
    unreadCount: 0,
    createdAt: demoTime("11:01"),
    lastActivityAt: demoTime("11:02"),
    slaDueAt: null,
    slaPaused: true,
    aiSummary: "Cliente perguntou pelo pedido #CL2210. A IA informou que está em trânsito, com previsão até 29/09, e enviou o rastreio.",
    orderIds: ["CL2210"],
    timeline: [
      {
        id: "m-0401",
        type: "message",
        author: "customer",
        at: demoTime("11:01"),
        body: "Boa tarde, onde está meu pedido CL2210?",
      },
      {
        id: "e-0402",
        type: "event",
        kind: "lookup",
        at: demoTime("11:01"),
        text: "IA consultou o pedido #CL2210",
        detail: "Pago · Em trânsito · Previsão 29/09",
      },
      {
        id: "m-0403",
        type: "message",
        author: "ai",
        at: demoTime("11:02"),
        body: "Oi, Marcos! Seu pedido #CL2210 (Luminária Arco Pérola) está em trânsito: saiu do centro de distribuição de Cajamar em 24/09, e a previsão da transportadora é entregar até 29/09. O código de rastreio é TX8823016BR. Posso ajudar em algo mais?",
        delivery: "entregue",
        sources: [src.order("CL2210", "Status de envio, rastreio e previsão")],
      },
    ],
  },
  {
    id: "cv-05",
    ticketNumber: 4808,
    customerId: "cu-05",
    storeId: "aurora",
    channel: "email",
    subject: "Pedido não chegou",
    reason: "status_pedido",
    priority: "normal",
    state: "awaiting_order_info",
    assigneeId: null,
    tags: [],
    unreadCount: 0,
    createdAt: demoTime("12:40"),
    lastActivityAt: demoTime("12:41"),
    slaDueAt: null,
    slaPaused: true,
    aiSummary:
      "A cliente diz que um pedido da semana passada não chegou. Nenhum pedido foi encontrado para o e-mail do contato; a IA pediu o número do pedido.",
    orderIds: [],
    timeline: [
      {
        id: "m-0501",
        type: "message",
        author: "customer",
        at: demoTime("12:40"),
        body: "Fiz uma compra semana passada e não chegou ainda. Podem verificar?\n\nFernanda",
      },
      {
        id: "e-0502",
        type: "event",
        kind: "lookup",
        at: demoTime("12:40"),
        text: "IA não encontrou pedidos para este contato",
        detail: "Busca por e-mail sem resultados. A IA não supõe qual pedido é.",
      },
      {
        id: "m-0503",
        type: "message",
        author: "ai",
        at: demoTime("12:41"),
        body: "Olá, Fernanda! Vou verificar para você. Não encontrei pedidos vinculados a este e-mail. Você pode me informar o número do pedido? Ele começa com #AU e aparece no e-mail de confirmação da compra.\n\nLia, da Aurora Cosméticos",
        delivery: "entregue",
        sources: [src.rule("Pedido não identificado", "Sem pedido confirmado, a IA pede o número e não informa status.")],
      },
    ],
  },
  {
    id: "cv-06",
    ticketNumber: 4803,
    customerId: "cu-06",
    storeId: "trilha",
    channel: "whatsapp",
    subject: "Troca de tamanho — Bota Cânion",
    reason: "troca",
    priority: "alta",
    state: "human_assigned",
    assigneeId: "u-thiago",
    teamId: "t-logistica",
    tags: ["troca"],
    unreadCount: 0,
    createdAt: demoTime("10:15"),
    lastActivityAt: demoTime("10:50"),
    slaDueAt: demoTime("16:50"),
    slaPaused: false,
    handoff: {
      reason: "Cliente quer trocar a Bota Cânion 42 pelo tamanho 43.",
      rule: "Trocas de produto estão sujeitas a regras e validação da equipe.",
      at: demoTime("10:16"),
    },
    aiSummary:
      "Troca da Bota Cânion 42 por 43 (pedido #TO5498, entregue em 20/09, dentro do prazo de 30 dias). Thiago confirmou estoque e vai enviar a etiqueta de devolução.",
    orderIds: ["TO5498"],
    timeline: [
      {
        id: "m-0601",
        type: "message",
        author: "customer",
        at: demoTime("10:15"),
        body: "Quero trocar a bota tamanho 42 por 43",
      },
      {
        id: "e-0602",
        type: "event",
        kind: "lookup",
        at: demoTime("10:15"),
        text: "IA consultou o pedido #TO5498",
        detail: "Pago · Entregue em 20/09",
      },
      {
        id: "m-0603",
        type: "message",
        author: "ai",
        at: demoTime("10:16"),
        body: "Claro, Ricardo! Localizei o pedido #TO5498 com a Bota Cânion 42, entregue em 20/09, ainda dentro do prazo de 30 dias para troca. Trocas são confirmadas pela nossa equipe, então já encaminhei sua solicitação. Em breve alguém continua por aqui.",
        delivery: "lida",
        sources: [
          src.order("TO5498", "Data de entrega e item"),
          src.kb("kb-01", "Política de trocas e devoluções", "Seção “Prazos para troca”, versão 3"),
        ],
      },
      {
        id: "e-0604",
        type: "event",
        kind: "handoff",
        at: demoTime("10:16"),
        text: "IA encaminhou para revisão humana",
        detail: "Trocas de produto estão sujeitas a regras e validação da equipe.",
      },
      {
        id: "e-0605",
        type: "event",
        kind: "assigned",
        at: demoTime("10:40"),
        text: "Thiago Mendes assumiu a conversa",
        detail: "A IA fica pausada enquanto uma pessoa conduz.",
      },
      {
        id: "m-0606",
        type: "message",
        author: "agent",
        authorId: "u-thiago",
        at: demoTime("10:42"),
        body: "Oi, Ricardo, aqui é o Thiago. Temos o 43 em estoque. Vou gerar a etiqueta de devolução e te envio por aqui ainda hoje, combinado?",
        delivery: "lida",
      },
      {
        id: "n-0607",
        type: "note",
        authorId: "u-thiago",
        at: demoTime("10:43"),
        body: "Etiqueta reversa precisa ser gerada manualmente no painel da transportadora. Reservei o 43 no estoque.",
      },
      { id: "m-0608", type: "message", author: "customer", at: demoTime("10:50"), body: "Combinado, obrigado!" },
    ],
  },
  {
    id: "cv-07",
    ticketNumber: 4801,
    customerId: "cu-07",
    storeId: "lume",
    channel: "email",
    subject: "Nota fiscal do pedido CL2187",
    reason: "nota_fiscal",
    priority: "normal",
    state: "agent_error",
    assigneeId: null,
    tags: ["nota-fiscal"],
    unreadCount: 1,
    createdAt: demoTime("09:30"),
    lastActivityAt: demoTime("09:31"),
    slaDueAt: demoTime("10:30"),
    slaPaused: false,
    error: "Tempo esgotado ao consultar o pedido #CL2187 (3 tentativas). Nenhuma mensagem foi enviada ao cliente.",
    aiSummary: "A cliente pede a nota fiscal do pedido #CL2187 para reembolso de despesas da empresa.",
    aiSuggestion:
      "O conteúdo “Emissão de nota fiscal” está em rascunho na base de conhecimento e não está disponível para o agente. Publicá-lo permite que a IA responda casos parecidos.",
    orderIds: ["CL2187"],
    timeline: [
      {
        id: "m-0701",
        type: "message",
        author: "customer",
        at: demoTime("09:30"),
        body: "Bom dia! Preciso da nota fiscal do pedido CL2187 para pedir reembolso na empresa. Podem me enviar?\n\nAline Souza",
      },
      {
        id: "e-0702",
        type: "event",
        kind: "classified",
        at: demoTime("09:30"),
        text: "IA classificou o contato",
        detail: "Motivo: nota fiscal · Prioridade: normal",
      },
      {
        id: "e-0703",
        type: "event",
        kind: "error",
        at: demoTime("09:31"),
        text: "O agente não conseguiu responder",
        detail: "Tempo esgotado ao consultar o pedido #CL2187 (3 tentativas). Nenhuma mensagem foi enviada.",
      },
    ],
  },
  {
    id: "cv-08",
    ticketNumber: 4807,
    customerId: "cu-08",
    storeId: "aurora",
    channel: "whatsapp",
    subject: "Atraso na entrega — pedido #AU1019",
    reason: "reclamacao",
    priority: "urgente",
    state: "needs_review",
    assigneeId: null,
    teamId: "t-revisao",
    tags: ["atraso", "procon"],
    unreadCount: 1,
    createdAt: demoTime("12:05"),
    lastActivityAt: demoTime("12:06"),
    slaDueAt: demoTime("12:35"),
    slaPaused: false,
    handoff: {
      reason: "Cliente mencionou o Procon e relata atraso recorrente.",
      rule: "Reclamação formal ou menção a órgãos de defesa do consumidor sempre vai para uma pessoa.",
      at: demoTime("12:06"),
    },
    aiSummary:
      "Terceiro contato sobre o pedido #AU1019, com previsão de entrega em 19/09 e sem atualização desde 16/09. O cliente ameaça registrar reclamação no Procon.",
    aiSuggestion:
      "Verificar com a transportadora o pedido #AU1019. Reenvio ou reembolso estão sujeitos a regras e validação da equipe.",
    orderIds: ["AU1019"],
    timeline: [
      {
        id: "m-0801",
        type: "message",
        author: "customer",
        at: demoTime("12:05"),
        body: "Já é a terceira vez que eu pergunto do meu pedido e ninguém resolve. Se não tiver resposta hoje vou abrir reclamação no Procon.",
      },
      {
        id: "e-0802",
        type: "event",
        kind: "classified",
        at: demoTime("12:05"),
        text: "IA classificou o contato",
        detail: "Motivo: reclamação · Prioridade: urgente · Tags: atraso, procon",
      },
      {
        id: "e-0803",
        type: "event",
        kind: "lookup",
        at: demoTime("12:05"),
        text: "IA consultou o pedido #AU1019",
        detail: "Pago · Em trânsito · Previsão 19/09 (vencida) · Última atualização 16/09",
      },
      {
        id: "m-0804",
        type: "message",
        author: "ai",
        at: demoTime("12:06"),
        body: "Bruno, entendo sua frustração e peço desculpas pela demora. Seu pedido #AU1019 está com a entrega atrasada: a última atualização da transportadora é de 16/09. Encaminhei sua conversa com prioridade para uma pessoa da equipe, que vai te responder por aqui.",
        delivery: "lida",
        sources: [
          src.order("AU1019", "Rastreio e previsão de entrega"),
          src.rule("Transferência obrigatória", "Menção a órgãos de defesa do consumidor"),
        ],
      },
      {
        id: "e-0805",
        type: "event",
        kind: "handoff",
        at: demoTime("12:06"),
        text: "IA encaminhou para revisão humana",
        detail: "Reclamação formal ou menção a órgãos de defesa do consumidor sempre vai para uma pessoa.",
      },
    ],
  },
  {
    id: "cv-09",
    ticketNumber: 4802,
    customerId: "cu-09",
    storeId: "lume",
    channel: "whatsapp",
    subject: "Refil para difusor Brisa",
    reason: "duvida_produto",
    priority: "baixa",
    state: "auto_resolved",
    assigneeId: null,
    tags: [],
    unreadCount: 0,
    createdAt: demoTime("09:12"),
    lastActivityAt: demoTime("09:20"),
    slaDueAt: null,
    slaPaused: false,
    aiSummary: "A cliente perguntou se há refil para o Difusor Brisa. A IA indicou o Refil Brisa 250 ml e a cliente encerrou.",
    orderIds: ["CL2150"],
    timeline: [
      {
        id: "m-0901",
        type: "message",
        author: "customer",
        at: demoTime("09:12"),
        body: "Vocês vendem refil para o difusor Brisa?",
      },
      {
        id: "m-0902",
        type: "message",
        author: "ai",
        at: demoTime("09:12"),
        body: "Oi, Carla! Sim, temos o Refil Brisa 250 ml nas fragrâncias Alecrim e Bambu, compatível com o Difusor Brisa. Quer o link do produto?",
        delivery: "lida",
        sources: [
          src.product("Refil Brisa 250 ml", "Catálogo da loja: variantes e disponibilidade"),
          src.kb("kb-05", "Catálogo: difusores e refis", "Compatibilidade, versão 1"),
        ],
      },
      { id: "m-0903", type: "message", author: "customer", at: demoTime("09:18"), body: "Não precisa, obrigada!" },
      {
        id: "m-0904",
        type: "message",
        author: "ai",
        at: demoTime("09:18"),
        body: "Por nada! Se precisar, é só chamar.",
        delivery: "lida",
      },
      {
        id: "e-0905",
        type: "event",
        kind: "resolved",
        at: demoTime("09:20"),
        text: "IA marcou como resolvida",
        detail: "Dúvida respondida e cliente encerrou a conversa.",
      },
    ],
  },
  {
    id: "cv-10",
    ticketNumber: 4800,
    customerId: "cu-10",
    storeId: "aurora",
    channel: "email",
    subject: "Código de rastreio",
    reason: "rastreamento",
    priority: "normal",
    state: "auto_resolved",
    assigneeId: null,
    tags: ["rastreio"],
    unreadCount: 0,
    createdAt: demoTime("08:12"),
    lastActivityAt: demoTime("08:40"),
    slaDueAt: null,
    slaPaused: false,
    aiSummary: "O cliente pediu o rastreio do pedido #AU1050. A IA enviou código e previsão; o cliente agradeceu.",
    orderIds: ["AU1050"],
    timeline: [
      {
        id: "m-1001",
        type: "message",
        author: "customer",
        at: demoTime("08:12"),
        body: "Olá, podem me passar o código de rastreio do pedido AU1050?\n\nGustavo",
      },
      {
        id: "e-1002",
        type: "event",
        kind: "lookup",
        at: demoTime("08:12"),
        text: "IA consultou o pedido #AU1050",
        detail: "Pago · Em trânsito · Previsão 27/09",
      },
      {
        id: "m-1003",
        type: "message",
        author: "ai",
        at: demoTime("08:13"),
        body: "Olá, Gustavo! Seu pedido #AU1050 foi postado em 23/09. O código de rastreio é TX5539028BR e a previsão da transportadora é entregar até 27/09.\n\nLia, da Aurora Cosméticos",
        delivery: "entregue",
        sources: [src.order("AU1050", "Rastreio e previsão de entrega")],
      },
      { id: "m-1004", type: "message", author: "customer", at: demoTime("08:35"), body: "Perfeito, obrigado!" },
      {
        id: "e-1005",
        type: "event",
        kind: "resolved",
        at: demoTime("08:40"),
        text: "IA marcou como resolvida",
        detail: "Dúvida respondida e cliente confirmou.",
      },
    ],
  },
  {
    id: "cv-11",
    ticketNumber: 4815,
    customerId: "cu-11",
    storeId: "aurora",
    channel: "email",
    subject: "Mudança de endereço de entrega",
    reason: "alteracao_endereco",
    priority: "normal",
    state: "human_assigned",
    assigneeId: "u-marina",
    teamId: "t-revisao",
    tags: ["endereco"],
    unreadCount: 1,
    createdAt: demoTime("13:40"),
    lastActivityAt: demoTime("14:05"),
    slaDueAt: demoTime("14:35"),
    slaPaused: false,
    handoff: {
      reason: "Cliente quer alterar o endereço de entrega de um pedido ainda não enviado.",
      rule: "Alterações de endereço estão sujeitas a regras e validação da equipe.",
      at: demoTime("13:41"),
    },
    aiSummary:
      "Pedido #AU1057 pago e ainda não enviado. A cliente se mudou e informou um novo endereço em Belo Horizonte. A alteração precisa ser validada e feita pela equipe.",
    orderIds: ["AU1057"],
    timeline: [
      {
        id: "m-1101",
        type: "message",
        author: "customer",
        at: demoTime("13:40"),
        body: "Olá! Me mudei esta semana. Consigo alterar o endereço de entrega do pedido AU1057?\n\nPatrícia",
      },
      {
        id: "e-1102",
        type: "event",
        kind: "lookup",
        at: demoTime("13:40"),
        text: "IA consultou o pedido #AU1057",
        detail: "Pago · Não enviado",
      },
      {
        id: "m-1103",
        type: "message",
        author: "ai",
        at: demoTime("13:41"),
        body: "Olá, Patrícia! Seu pedido #AU1057 ainda não foi enviado, então a alteração pode ser avaliada. Alterações de endereço são confirmadas pela nossa equipe, e já encaminhei sua solicitação. Pode responder este e-mail com o novo endereço completo e o CEP.\n\nLia, da Aurora Cosméticos",
        delivery: "entregue",
        sources: [
          src.order("AU1057", "Status de envio"),
          src.kb("kb-06", "Política de alteração de pedidos", "Seção “Endereço de entrega”, versão 2"),
        ],
      },
      {
        id: "e-1104",
        type: "event",
        kind: "handoff",
        at: demoTime("13:41"),
        text: "IA encaminhou para revisão humana",
        detail: "Alterações de endereço estão sujeitas a regras e validação da equipe.",
      },
      {
        id: "e-1105",
        type: "event",
        kind: "assigned",
        at: demoTime("13:55"),
        text: "Marina Costa assumiu a conversa",
        detail: "A IA fica pausada enquanto uma pessoa conduz.",
      },
      {
        id: "m-1106",
        type: "message",
        author: "customer",
        at: demoTime("14:05"),
        body: "Novo endereço: Rua das Palmeiras, 1•• — ap. 3•, Belo Horizonte/MG, CEP 30•••-120.",
      },
    ],
  },
  {
    id: "cv-12",
    ticketNumber: 4806,
    customerId: "cu-12",
    storeId: "lume",
    channel: "whatsapp",
    subject: "Pix pago, pedido pendente",
    reason: "pagamento",
    priority: "alta",
    state: "agent_paused",
    assigneeId: null,
    teamId: "t-financeiro",
    tags: ["pix"],
    unreadCount: 0,
    createdAt: demoTime("11:30"),
    lastActivityAt: demoTime("11:40"),
    slaDueAt: demoTime("15:40"),
    slaPaused: false,
    pausedBy: "u-rafael",
    aiSummary:
      "O cliente diz ter pago o Pix do pedido #CL2231, que segue com pagamento pendente na loja. Enviou comprovante e pediu para falar com uma pessoa.",
    orderIds: ["CL2231"],
    timeline: [
      {
        id: "m-1201",
        type: "message",
        author: "customer",
        at: demoTime("11:30"),
        body: "Paguei o Pix mas o pedido aparece como pendente",
      },
      {
        id: "e-1202",
        type: "event",
        kind: "lookup",
        at: demoTime("11:30"),
        text: "IA consultou o pedido #CL2231",
        detail: "Pagamento pendente · Não enviado",
      },
      {
        id: "m-1203",
        type: "message",
        author: "ai",
        at: demoTime("11:31"),
        body: "Oi, Rodrigo! O pedido #CL2231 ainda consta com pagamento pendente na loja. Pode me enviar o comprovante do Pix? Vou encaminhar para a equipe financeira conferir.",
        delivery: "lida",
        sources: [
          src.order("CL2231", "Status de pagamento"),
          src.kb("kb-10", "Formas de pagamento e Pix", "Seção “Pix não confirmado”, versão 1"),
        ],
      },
      {
        id: "m-1204",
        type: "message",
        author: "customer",
        at: demoTime("11:33"),
        body: "Segue. Quero falar com uma pessoa, por favor.",
        attachments: [{ name: "comprovante-pix.pdf", kind: "pdf", size: "142 KB" }],
      },
      {
        id: "e-1205",
        type: "event",
        kind: "transferred",
        at: demoTime("11:33"),
        text: "IA transferiu para a equipe Financeiro",
        detail: "O cliente pediu atendimento humano.",
      },
      {
        id: "e-1206",
        type: "event",
        kind: "paused",
        at: demoTime("11:40"),
        text: "Rafael Nunes pausou a IA nesta conversa",
        detail: "Aguardando conferência do comprovante pelo financeiro.",
      },
      {
        id: "n-1207",
        type: "note",
        authorId: "u-rafael",
        at: demoTime("11:41"),
        body: "@Camila, pode conferir no extrato se o Pix de R$ 948,90 entrou? Ainda não aparece como pago na loja.",
      },
    ],
  },
  {
    id: "cv-13",
    ticketNumber: 4816,
    customerId: "cu-13",
    storeId: "aurora",
    channel: "whatsapp",
    subject: "Cupom para cliente que já comprou",
    reason: "cupom",
    priority: "baixa",
    state: "ai_active",
    assigneeId: null,
    tags: ["cupom"],
    unreadCount: 0,
    createdAt: demoTime("14:12"),
    lastActivityAt: demoTime("14:26"),
    slaDueAt: demoTime("14:56"),
    slaPaused: false,
    aiSummary:
      "A cliente perguntou se o BEMVINDA10 vale para quem já comprou. A IA explicou que não e indicou o cupom ativo para recompra; ela perguntou se vale para o kit presente.",
    orderIds: ["AU0950"],
    timeline: [
      {
        id: "m-1301",
        type: "message",
        author: "customer",
        at: demoTime("14:12"),
        body: "O cupom BEMVINDA10 vale pra quem já comprou antes?",
      },
      {
        id: "m-1302",
        type: "message",
        author: "ai",
        at: demoTime("14:13"),
        body: "Oi, Mariana! O BEMVINDA10 vale só para a primeira compra na Aurora, e você já tem um pedido conosco (#AU0950, de julho). Para quem já comprou, o cupom ativo é o VOLTEI15: 15% de desconto em compras acima de R$ 150, até 30/09. Quer que eu explique como aplicar?",
        delivery: "lida",
        sources: [
          src.kb("kb-04", "Regras de cupons e promoções", "Cupons ativos em setembro, versão 4"),
          src.order("AU0950", "Histórico de compras do contato"),
        ],
      },
      { id: "m-1303", type: "message", author: "customer", at: demoTime("14:26"), body: "Quero! E vale pro kit presente?" },
    ],
  },
  {
    id: "cv-14",
    ticketNumber: 4811,
    customerId: "cu-14",
    storeId: "trilha",
    channel: "whatsapp",
    subject: "Alça da mochila rasgou",
    reason: "produto_danificado",
    priority: "normal",
    state: "awaiting_customer",
    assigneeId: null,
    tags: ["defeito"],
    unreadCount: 0,
    createdAt: demoTime("13:15"),
    lastActivityAt: demoTime("13:16"),
    slaDueAt: null,
    slaPaused: true,
    aiSummary:
      "A alça da Mochila Cume 40 L (pedido #TO5512, entregue em 22/09) rasgou na costura. A IA pediu duas fotos para abrir a análise de garantia.",
    orderIds: ["TO5512"],
    timeline: [
      {
        id: "m-1401",
        type: "message",
        author: "customer",
        at: demoTime("13:15"),
        body: "A alça da mochila Cume rasgou na costura com uma semana de uso",
      },
      {
        id: "e-1402",
        type: "event",
        kind: "classified",
        at: demoTime("13:15"),
        text: "IA classificou o contato",
        detail: "Motivo: produto com defeito · Prioridade: normal · Tag: defeito",
      },
      {
        id: "e-1403",
        type: "event",
        kind: "lookup",
        at: demoTime("13:15"),
        text: "IA consultou o pedido #TO5512",
        detail: "Pago · Entregue em 22/09",
      },
      {
        id: "m-1404",
        type: "message",
        author: "ai",
        at: demoTime("13:16"),
        body: "Poxa, Eduardo, sinto muito! Encontrei seu pedido #TO5512, com a Mochila Cume 40 L entregue em 22/09. Para abrir a análise de garantia, preciso de duas fotos: uma da alça inteira e outra da costura de perto. Pode enviar por aqui?",
        delivery: "entregue",
        sources: [
          src.order("TO5512", "Item e data de entrega"),
          src.kb("kb-01", "Política de trocas e devoluções", "Seção “Defeitos de fabricação”, versão 3"),
        ],
      },
    ],
  },
  {
    id: "cv-15",
    ticketNumber: 4796,
    customerId: "cu-15",
    storeId: "lume",
    channel: "email",
    subject: "Cancelar pedido CL2224",
    reason: "cancelamento",
    priority: "normal",
    state: "resolved",
    assigneeId: "u-bianca",
    teamId: "t-revisao",
    tags: [],
    unreadCount: 0,
    createdAt: demoTime("16:02", -1),
    lastActivityAt: demoTime("16:45", -1),
    slaDueAt: null,
    slaPaused: false,
    handoff: {
      reason: "Cliente pediu cancelamento de pedido não enviado.",
      rule: "Cancelamentos estão sujeitos a regras e validação da equipe.",
      at: demoTime("16:03", -1),
    },
    aiSummary:
      "Cancelamento do pedido #CL2224 antes do envio. Bianca cancelou e reembolsou manualmente no admin da loja e confirmou à cliente.",
    orderIds: ["CL2224"],
    timeline: [
      {
        id: "m-1501",
        type: "message",
        author: "customer",
        at: demoTime("16:02", -1),
        body: "Oi, fiz o pedido ontem mas me arrependi. Consigo cancelar?\n\nSofia",
      },
      {
        id: "e-1502",
        type: "event",
        kind: "lookup",
        at: demoTime("16:02", -1),
        text: "IA consultou o pedido #CL2224",
        detail: "Pago · Não enviado",
      },
      {
        id: "m-1503",
        type: "message",
        author: "ai",
        at: demoTime("16:03", -1),
        body: "Olá, Sofia! Seu pedido #CL2224 ainda não foi enviado. Cancelamentos são confirmados pela nossa equipe; já encaminhei sua solicitação e você recebe a confirmação por e-mail.\n\nLia, da Casa Lume",
        delivery: "entregue",
        sources: [
          src.order("CL2224", "Status de envio"),
          src.kb("kb-06", "Política de alteração de pedidos", "Seção “Cancelamento”, versão 2"),
        ],
      },
      {
        id: "e-1504",
        type: "event",
        kind: "handoff",
        at: demoTime("16:03", -1),
        text: "IA encaminhou para revisão humana",
        detail: "Cancelamentos estão sujeitos a regras e validação da equipe.",
      },
      {
        id: "e-1505",
        type: "event",
        kind: "assigned",
        at: demoTime("16:20", -1),
        text: "Bianca Lopes assumiu a conversa",
      },
      {
        id: "n-1506",
        type: "note",
        authorId: "u-bianca",
        at: demoTime("16:31", -1),
        body: "Cancelado e reembolsado manualmente no admin da loja. Nada foi executado pelo Suportfy.",
      },
      {
        id: "m-1507",
        type: "message",
        author: "agent",
        authorId: "u-bianca",
        at: demoTime("16:33", -1),
        body: "Oi, Sofia! Seu pedido #CL2224 foi cancelado e o reembolso de R$ 629,00 foi solicitado para o seu cartão. O estorno pode levar até duas faturas para aparecer, conforme a operadora.\n\nBianca, da Casa Lume",
        delivery: "entregue",
      },
      { id: "m-1508", type: "message", author: "customer", at: demoTime("16:40", -1), body: "Obrigada!" },
      {
        id: "e-1509",
        type: "event",
        kind: "resolved",
        at: demoTime("16:45", -1),
        text: "Bianca Lopes resolveu a conversa",
      },
    ],
  },
  {
    id: "cv-16",
    ticketNumber: 4814,
    customerId: "cu-16",
    storeId: "lume",
    channel: "whatsapp",
    subject: "Entrega para Manaus",
    reason: "prazo_entrega",
    priority: "normal",
    state: "ai_active",
    assigneeId: null,
    tags: [],
    unreadCount: 1,
    createdAt: demoTime("14:20"),
    lastActivityAt: demoTime("14:29"),
    slaDueAt: demoTime("14:59"),
    slaPaused: false,
    aiSummary:
      "Pergunta sobre entrega em Manaus. A IA informou o prazo da região Norte; a cliente agora pergunta a partir de qual valor o frete é grátis.",
    orderIds: [],
    timeline: [
      {
        id: "m-1601",
        type: "message",
        author: "customer",
        at: demoTime("14:20"),
        body: "Oi, vocês entregam em Manaus? Qual o prazo?",
      },
      {
        id: "m-1602",
        type: "message",
        author: "ai",
        at: demoTime("14:20"),
        body: "Oi, Helena! Entregamos, sim. Para a região Norte, o prazo é de 8 a 12 dias úteis após a confirmação do pagamento. O valor do frete aparece no carrinho a partir do CEP. Posso ajudar a escolher algum produto?",
        delivery: "lida",
        sources: [src.kb("kb-02", "Prazos de entrega por região", "Região Norte, versão 2")],
      },
      {
        id: "m-1603",
        type: "message",
        author: "customer",
        at: demoTime("14:29"),
        body: "E o frete é grátis acima de quanto?",
      },
    ],
  },
  {
    id: "cv-17",
    ticketNumber: 4702,
    customerId: "cu-08",
    storeId: "aurora",
    channel: "whatsapp",
    subject: "Rastreio do pedido #AU1019",
    reason: "rastreamento",
    priority: "normal",
    state: "auto_resolved",
    assigneeId: null,
    tags: ["rastreio"],
    unreadCount: 0,
    createdAt: demoDate(12, 9, "18:30"),
    lastActivityAt: demoDate(12, 9, "18:42"),
    slaDueAt: null,
    slaPaused: false,
    aiSummary: "O cliente pediu o rastreio do pedido #AU1019. A IA enviou código e previsão (19/09).",
    orderIds: ["AU1019"],
    timeline: [
      {
        id: "m-1701",
        type: "message",
        author: "customer",
        at: demoDate(12, 9, "18:30"),
        body: "Oi, já enviaram meu pedido?",
      },
      {
        id: "m-1702",
        type: "message",
        author: "ai",
        at: demoDate(12, 9, "18:31"),
        body: "Oi, Bruno! Sim, seu pedido #AU1019 foi postado hoje. O código de rastreio é TX9014427BR, e a previsão da transportadora é entregar até 19/09.",
        delivery: "lida",
        sources: [src.order("AU1019", "Postagem e previsão de entrega")],
      },
      { id: "m-1703", type: "message", author: "customer", at: demoDate(12, 9, "18:40"), body: "Valeu" },
      {
        id: "e-1704",
        type: "event",
        kind: "resolved",
        at: demoDate(12, 9, "18:42"),
        text: "IA marcou como resolvida",
      },
    ],
  },
  {
    id: "cv-18",
    ticketNumber: 4751,
    customerId: "cu-08",
    storeId: "aurora",
    channel: "whatsapp",
    subject: "Pedido #AU1019 parado",
    reason: "status_pedido",
    priority: "alta",
    state: "resolved",
    assigneeId: "u-bianca",
    teamId: "t-revisao",
    tags: ["atraso"],
    unreadCount: 0,
    createdAt: demoDate(18, 9, "14:50"),
    lastActivityAt: demoDate(18, 9, "15:25"),
    slaDueAt: null,
    slaPaused: false,
    handoff: {
      reason: "Rastreio sem atualização há mais de 48 horas.",
      rule: "Atrasos sem atualização da transportadora vão para uma pessoa.",
      at: demoDate(18, 9, "14:51"),
    },
    aiSummary: "O pedido #AU1019 estava sem atualização desde 16/09. Bianca abriu chamado com a transportadora.",
    orderIds: ["AU1019"],
    timeline: [
      {
        id: "m-1801",
        type: "message",
        author: "customer",
        at: demoDate(18, 9, "14:50"),
        body: "Meu pedido está parado desde terça. O que houve?",
      },
      {
        id: "m-1802",
        type: "message",
        author: "ai",
        at: demoDate(18, 9, "14:51"),
        body: "Oi, Bruno! Vi que o rastreio do pedido #AU1019 não é atualizado desde 16/09. Encaminhei para a equipe verificar com a transportadora e te respondemos por aqui.",
        delivery: "lida",
        sources: [src.order("AU1019", "Histórico de rastreio")],
      },
      {
        id: "e-1803",
        type: "event",
        kind: "handoff",
        at: demoDate(18, 9, "14:51"),
        text: "IA encaminhou para revisão humana",
        detail: "Atrasos sem atualização da transportadora vão para uma pessoa.",
      },
      {
        id: "m-1804",
        type: "message",
        author: "agent",
        authorId: "u-bianca",
        at: demoDate(18, 9, "15:20"),
        body: "Oi, Bruno, aqui é a Bianca. Abri um chamado com a transportadora e te aviso assim que tiver retorno.",
        delivery: "lida",
      },
      {
        id: "e-1805",
        type: "event",
        kind: "resolved",
        at: demoDate(18, 9, "15:25"),
        text: "Bianca Lopes resolveu a conversa",
      },
    ],
  },
];

export const knowledgeItems: KnowledgeItem[] = [
  {
    id: "kb-01",
    title: "Política de trocas e devoluções",
    type: "politica",
    status: "publicado",
    storeIds: "all",
    source: { kind: "manual", label: "Copiado da página de políticas da loja" },
    version: 3,
    versions: [
      { version: 3, at: demoDate(12, 9, "10:20"), authorId: "u-marina", note: "Inclui prazo para produto danificado na entrega." },
      { version: 2, at: demoDate(4, 8, "16:00"), authorId: "u-rafael", note: "Ajuste no prazo de troca para 30 dias." },
      { version: 1, at: demoDate(20, 6, "09:00"), authorId: "u-marina", note: "Primeira versão." },
    ],
    updatedAt: demoDate(12, 9, "10:20"),
    updatedBy: "u-marina",
    content:
      "Prazos para troca\nTrocas podem ser solicitadas em até 30 dias após a entrega, com o produto sem sinais de uso.\n\nProduto danificado na entrega\nO cliente deve avisar em até 7 dias e enviar foto do produto e da embalagem. O item pode ser reembolsado ou reenviado, a critério do cliente, após validação da equipe.\n\nDefeitos de fabricação\nPara abrir análise de garantia, solicitar fotos do defeito. A análise leva até 5 dias úteis.\n\nReembolsos\nReembolsos são sempre aprovados por uma pessoa da equipe. O agente de IA não promete valores nem prazos de estorno.",
  },
  {
    id: "kb-02",
    title: "Prazos de entrega por região",
    type: "documento",
    status: "publicado",
    storeIds: "all",
    source: { kind: "upload", label: "tabela-prazos-2026.pdf (enviado manualmente)" },
    version: 2,
    versions: [
      { version: 2, at: demoDate(1, 9, "14:10"), authorId: "u-rafael", note: "Atualização da tabela da transportadora." },
      { version: 1, at: demoDate(20, 6, "09:30"), authorId: "u-marina", note: "Primeira versão." },
    ],
    updatedAt: demoDate(1, 9, "14:10"),
    updatedBy: "u-rafael",
    content:
      "Prazos após a confirmação do pagamento (dias úteis):\n• Sudeste: 3 a 6\n• Sul: 4 a 7\n• Centro-Oeste: 5 a 8\n• Nordeste: 6 a 10\n• Norte: 8 a 12\n\nO valor do frete é calculado no carrinho a partir do CEP. O agente não informa valores de frete sem consultar o carrinho.",
  },
  {
    id: "kb-03",
    title: "Guia de uso: Linha Vitamina C",
    type: "documento",
    status: "publicado",
    storeIds: ["aurora"],
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 1,
    versions: [{ version: 1, at: demoDate(15, 8, "11:00"), authorId: "u-bianca", note: "Primeira versão." }],
    updatedAt: demoDate(15, 8, "11:00"),
    updatedBy: "u-bianca",
    content:
      "Rotina recomendada\nAplicar o Sérum Vitamina C pela manhã, sobre a pele limpa, seguido de protetor solar.\n\nCombinações\nEvitar aplicar ácidos (glicólico, salicílico) na mesma rotina da Vitamina C. Preferir ácidos à noite.\n\nArmazenamento\nManter o frasco fechado, longe da luz e do calor.",
  },
  {
    id: "kb-04",
    title: "Regras de cupons e promoções",
    type: "faq",
    status: "publicado",
    storeIds: ["aurora"],
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 4,
    versions: [
      { version: 4, at: demoDate(1, 9, "08:00"), authorId: "u-marina", note: "Cupons de setembro." },
      { version: 3, at: demoDate(1, 8, "08:00"), authorId: "u-marina", note: "Cupons de agosto." },
    ],
    updatedAt: demoDate(1, 9, "08:00"),
    updatedBy: "u-marina",
    content:
      "BEMVINDA10 — 10% na primeira compra. Não vale para quem já tem pedido.\n\nVOLTEI15 — 15% para quem já comprou, em pedidos acima de R$ 150. Válido até 30/09.\n\nCupons não são cumulativos e não valem para kits em promoção, salvo indicação na página do produto.",
  },
  {
    id: "kb-05",
    title: "Catálogo: difusores e refis",
    type: "faq",
    status: "publicado",
    storeIds: ["lume"],
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 1,
    versions: [{ version: 1, at: demoDate(3, 8, "15:00"), authorId: "u-bianca", note: "Primeira versão." }],
    updatedAt: demoDate(3, 8, "15:00"),
    updatedBy: "u-bianca",
    content:
      "O Difusor Brisa usa o Refil Brisa 250 ml (fragrâncias Alecrim e Bambu). O Difusor Aurora de cerâmica não é compatível com refis de outras linhas.\n\nDisponibilidade e preço devem ser confirmados no catálogo da loja no momento da conversa.",
  },
  {
    id: "kb-06",
    title: "Política de alteração de pedidos",
    type: "politica",
    status: "publicado",
    storeIds: "all",
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 2,
    versions: [
      { version: 2, at: demoDate(28, 8, "17:30"), authorId: "u-rafael", note: "Cancelamento sujeito a validação." },
      { version: 1, at: demoDate(20, 6, "10:00"), authorId: "u-marina", note: "Primeira versão." },
    ],
    updatedAt: demoDate(28, 8, "17:30"),
    updatedBy: "u-rafael",
    content:
      "Endereço de entrega\nPode ser alterado enquanto o pedido não for enviado. A alteração é feita pela equipe, nunca pelo agente.\n\nCancelamento\nPedidos não enviados podem ser cancelados após validação da equipe. O agente registra a solicitação e encaminha.",
  },
  {
    id: "kb-07",
    title: "Cuidados com barracas e equipamentos",
    type: "documento",
    status: "rascunho",
    storeIds: ["trilha"],
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 1,
    versions: [{ version: 1, at: demoDate(22, 9, "16:40"), authorId: "u-thiago", note: "Rascunho inicial." }],
    updatedAt: demoDate(22, 9, "16:40"),
    updatedBy: "u-thiago",
    content:
      "Secagem\nNunca guardar a barraca molhada. Montar em local ventilado até secar completamente.\n\nLimpeza\nUsar apenas água e sabão neutro. Não lavar em máquina.",
  },
  {
    id: "kb-08",
    title: "Garantia de calçados",
    type: "politica",
    status: "rascunho",
    storeIds: ["trilha"],
    source: { kind: "url", label: "Página “Garantia” do site da loja" },
    version: 1,
    versions: [{ version: 1, at: demoDate(19, 9, "10:10"), authorId: "u-thiago", note: "Importado para revisão." }],
    updatedAt: demoDate(19, 9, "10:10"),
    updatedBy: "u-thiago",
    content: "Calçados têm garantia de 90 dias contra defeitos de fabricação. Desgaste natural não é coberto.",
  },
  {
    id: "kb-09",
    title: "Regras da Black Friday 2025",
    type: "faq",
    status: "arquivado",
    storeIds: ["aurora"],
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 3,
    versions: [{ version: 3, at: demoDate(20, 11, "09:00", 2025), authorId: "u-marina", note: "Versão final da campanha." }],
    updatedAt: demoDate(2, 12, "09:00", 2025),
    updatedBy: "u-marina",
    content: "Campanha encerrada. Conteúdo mantido apenas para consulta.",
  },
  {
    id: "kb-10",
    title: "Formas de pagamento e Pix",
    type: "faq",
    status: "publicado",
    storeIds: "all",
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 1,
    versions: [{ version: 1, at: demoDate(10, 7, "11:00"), authorId: "u-camila", note: "Primeira versão." }],
    updatedAt: demoDate(10, 7, "11:00"),
    updatedBy: "u-camila",
    content:
      "Aceitamos cartão de crédito (até 6x), Pix e boleto.\n\nPix não confirmado\nA confirmação costuma levar alguns minutos. Se o pedido seguir pendente, solicitar o comprovante e encaminhar ao financeiro. O agente não confirma pagamentos por conta própria.",
  },
  {
    id: "kb-11",
    title: "Emissão de nota fiscal",
    type: "faq",
    status: "rascunho",
    storeIds: "all",
    source: { kind: "manual", label: "Escrito pela equipe" },
    version: 1,
    versions: [{ version: 1, at: demoDate(24, 9, "18:15"), authorId: "u-camila", note: "Rascunho para revisão do financeiro." }],
    updatedAt: demoDate(24, 9, "18:15"),
    updatedBy: "u-camila",
    content:
      "A nota fiscal é enviada ao e-mail do comprador quando o pedido é faturado. Para segunda via, a equipe financeira reenvia o arquivo em até 2 dias úteis.",
  },
];

export const automations: Automation[] = [
  {
    id: "au-01",
    name: "Encaminhar reembolsos ao financeiro",
    description: "Quando a IA identifica pedido de reembolso, marca e envia para a equipe Financeiro.",
    trigger: "ia_classificou",
    storeId: "all",
    state: "ativa",
    conditions: [{ field: "motivo", operator: "é", value: "Reembolso" }],
    actions: [
      { type: "adicionar_tag", value: "reembolso" },
      { type: "atribuir_equipe", value: "Financeiro" },
    ],
    lastRun: { at: demoTime("13:57"), result: "sucesso", detail: "Conversa #4812 marcada e atribuída." },
  },
  {
    id: "au-02",
    name: "Priorizar clientes VIP",
    description: "Conversas de clientes com a tag VIP entram com prioridade alta.",
    trigger: "nova_conversa",
    storeId: "all",
    state: "ativa",
    conditions: [{ field: "tag_cliente", operator: "contém", value: "vip" }],
    actions: [{ type: "definir_prioridade", value: "Alta" }],
    lastRun: { at: demoTime("14:24"), result: "sem_acao", detail: "Cliente sem a tag VIP; nenhuma ação." },
  },
  {
    id: "au-03",
    name: "Avisar supervisor quando o SLA estiver em risco",
    description: "Notifica o supervisor 30 minutos antes do vencimento do SLA.",
    trigger: "sla_em_risco",
    storeId: "all",
    state: "ativa",
    conditions: [{ field: "estado", operator: "é", value: "Precisa de revisão" }],
    actions: [{ type: "notificar", value: "Rafael Nunes" }],
    lastRun: { at: demoTime("14:18"), result: "sucesso", detail: "Notificação registrada para a conversa #4812." },
  },
  {
    id: "au-04",
    name: "Pesquisa de satisfação após resolução",
    description: "Envia o template de pesquisa uma hora depois que a conversa é resolvida.",
    trigger: "conversa_resolvida",
    storeId: "aurora",
    state: "pausada",
    conditions: [{ field: "canal", operator: "é", value: "WhatsApp" }],
    actions: [{ type: "enviar_template", value: "Pesquisa de satisfação" }],
    lastRun: { at: demoDate(20, 9, "17:02"), result: "falhou", detail: "Template sem variável obrigatória {{cliente.nome}}." },
  },
  {
    id: "au-05",
    name: "Reclamações formais para revisão",
    description: "Mensagens que citam Procon ou Reclame Aqui vão direto para revisão com prioridade urgente.",
    trigger: "mensagem_recebida",
    storeId: "all",
    state: "ativa",
    conditions: [{ field: "mensagem", operator: "contém", value: "procon, reclame aqui" }],
    actions: [
      { type: "definir_prioridade", value: "Urgente" },
      { type: "encaminhar_revisao", value: "Revisão e exceções" },
    ],
    lastRun: { at: demoTime("12:05"), result: "sucesso", detail: "Conversa #4807 priorizada." },
  },
  {
    id: "au-06",
    name: "Lembrete de Pix pendente",
    description: "Envia um lembrete quando o pagamento Pix segue pendente depois de 24 horas.",
    trigger: "pedido_atualizado",
    storeId: "lume",
    state: "rascunho",
    conditions: [
      { field: "pagamento", operator: "é", value: "Pendente" },
      { field: "forma_pagamento", operator: "é", value: "Pix" },
    ],
    actions: [{ type: "enviar_template", value: "Lembrete de pagamento" }],
  },
];

export const quickReplies: QuickReply[] = [
  {
    id: "qr-01",
    shortcut: "/rastreio",
    title: "Enviar rastreio",
    body: "Oi, {{cliente.primeiro_nome}}! O código de rastreio do pedido {{pedido.numero}} é {{pedido.rastreio}}. A previsão da transportadora é {{pedido.previsao}}.",
    storeId: "all",
  },
  {
    id: "qr-02",
    shortcut: "/reembolso-analise",
    title: "Reembolso em análise",
    body: "{{cliente.primeiro_nome}}, seu pedido de reembolso está em análise pela nossa equipe. Você recebe a confirmação por aqui assim que for concluído.",
    storeId: "all",
  },
  {
    id: "qr-03",
    shortcut: "/troca",
    title: "Instruções de troca",
    body: "Para a troca, vamos te enviar uma etiqueta de devolução. Embale o produto na caixa original e poste em até 7 dias.",
    storeId: "all",
  },
  {
    id: "qr-04",
    shortcut: "/endereco-ok",
    title: "Endereço atualizado",
    body: "Pronto, {{cliente.primeiro_nome}}! O endereço de entrega do pedido {{pedido.numero}} foi atualizado.",
    storeId: "all",
  },
  {
    id: "qr-05",
    shortcut: "/nf",
    title: "Segunda via da nota fiscal",
    body: "Vamos reenviar a nota fiscal do pedido {{pedido.numero}} para o seu e-mail em até 2 dias úteis.",
    storeId: "all",
  },
  {
    id: "qr-06",
    shortcut: "/vitc",
    title: "Rotina com Vitamina C",
    body: "Use a Vitamina C pela manhã, seguida de protetor solar, e deixe os ácidos para a rotina da noite.",
    storeId: "aurora",
  },
];

export const tagDefinitions: TagDefinition[] = [
  { id: "tg-01", name: "reembolso", color: "#b02a20", description: "Pedidos de reembolso total ou parcial." },
  { id: "tg-02", name: "troca", color: "#875a00", description: "Troca de tamanho, cor ou produto." },
  { id: "tg-03", name: "produto-danificado", color: "#b4577a", description: "Produto chegou danificado." },
  { id: "tg-04", name: "defeito", color: "#7a4fb4", description: "Defeito de fabricação." },
  { id: "tg-05", name: "atraso", color: "#c0802a", description: "Entrega atrasada." },
  { id: "tg-06", name: "rastreio", color: "#1f6a80", description: "Pedidos de código ou status de rastreio." },
  { id: "tg-07", name: "pix", color: "#1b6f47", description: "Pagamentos via Pix." },
  { id: "tg-08", name: "procon", color: "#b02a20", description: "Menção a órgãos de defesa do consumidor." },
  { id: "tg-09", name: "endereco", color: "#434951", description: "Alteração de endereço." },
  { id: "tg-10", name: "nota-fiscal", color: "#434951", description: "Solicitações de nota fiscal." },
  { id: "tg-11", name: "cupom", color: "#2f7f96", description: "Dúvidas sobre cupons e promoções." },
];

export const messageTemplates: MessageTemplate[] = [
  {
    id: "tp-01",
    name: "Pesquisa de satisfação",
    channel: "whatsapp",
    category: "Pós-atendimento",
    status: "rascunho",
    body: "Oi, {{cliente.primeiro_nome}}! De 1 a 5, como foi seu atendimento hoje?",
  },
  {
    id: "tp-02",
    name: "Código de rastreio",
    channel: "email",
    category: "Pedidos",
    status: "ativo",
    body: "Olá, {{cliente.primeiro_nome}}!\n\nSeu pedido {{pedido.numero}} foi postado. Código de rastreio: {{pedido.rastreio}}.",
  },
  {
    id: "tp-03",
    name: "Reembolso aprovado",
    channel: "ambos",
    category: "Financeiro",
    status: "ativo",
    body: "{{cliente.primeiro_nome}}, o reembolso do pedido {{pedido.numero}} foi aprovado. O prazo de estorno depende da forma de pagamento.",
  },
  {
    id: "tp-04",
    name: "Retorno fora do horário",
    channel: "whatsapp",
    category: "Operação",
    status: "ativo",
    body: "Recebemos sua mensagem. Nossa equipe retorna no próximo horário de atendimento.",
  },
  {
    id: "tp-05",
    name: "Lembrete de pagamento",
    channel: "whatsapp",
    category: "Pedidos",
    status: "rascunho",
    body: "Oi, {{cliente.primeiro_nome}}! O pagamento do pedido {{pedido.numero}} ainda está pendente.",
  },
];

export const handoffCategories = [
  { id: "reembolso", label: "Reembolso" },
  { id: "cancelamento", label: "Cancelamento de pedido" },
  { id: "alteracao_endereco", label: "Alteração de endereço" },
  { id: "troca", label: "Troca de produto" },
  { id: "reclamacao", label: "Reclamação formal (Procon, Reclame Aqui)" },
  { id: "juridico", label: "Assuntos jurídicos" },
  { id: "pagamento", label: "Pagamento não confirmado" },
  { id: "dados_pessoais", label: "Pedidos sobre dados pessoais (LGPD)" },
];

export const initialAgentConfig: AgentConfig = {
  orgPaused: false,
  defaultMode: "auto",
  channels: {
    aurora: { whatsapp: { mode: "auto", paused: false }, email: { mode: "auto", paused: false } },
    lume: { whatsapp: { mode: "auto", paused: false }, email: { mode: "auto", paused: false } },
    trilha: { whatsapp: { mode: "auto", paused: false }, email: { mode: "copilot", paused: false } },
  },
  name: "Lia",
  signatureByStore: {
    aurora: "Lia, da Aurora Cosméticos",
    lume: "Lia, da Casa Lume",
    trilha: "Lia, da Trilha Outdoor",
  },
  tone: "cordial",
  length: "curta",
  instructions:
    "Trate o cliente pelo primeiro nome.\nConfirme o número do pedido antes de falar sobre status, pagamento ou entrega.\nNunca prometa prazos que não estejam no pedido ou na base de conhecimento.\nQuando não tiver informação suficiente, peça o dado que falta ou encaminhe para a equipe.",
  schedule: "sempre",
  maxAutoReplies: 8,
  handoffOnHumanRequest: true,
  handoffOnNegativeSentiment: true,
  handoffCategories: ["reembolso", "cancelamento", "alteracao_endereco", "troca", "reclamacao", "juridico", "dados_pessoais"],
  handoffTeamId: "t-revisao",
  knowledgeSources: Object.fromEntries(knowledgeItems.map((k) => [k.id, k.status === "publicado"])),
  shopifySources: { orders: true, products: true, customers: true },
};

export const initialAudit: AuditEntry[] = [
  {
    id: "au-l-1",
    at: demoTime("13:55"),
    actorId: "u-marina",
    action: "Assumiu a conversa",
    target: "Ticket #4815 · Patrícia Ramos",
  },
  {
    id: "au-l-2",
    at: demoTime("11:40"),
    actorId: "u-rafael",
    action: "Pausou a IA na conversa",
    target: "Ticket #4806 · Rodrigo Teixeira",
  },
  {
    id: "au-l-3",
    at: demoTime("10:40"),
    actorId: "u-thiago",
    action: "Assumiu a conversa",
    target: "Ticket #4803 · Ricardo Gomes",
  },
  {
    id: "au-l-4",
    at: demoTime("16:45", -1),
    actorId: "u-bianca",
    action: "Resolveu a conversa",
    target: "Ticket #4796 · Sofia Almeida",
  },
  {
    id: "au-l-5",
    at: demoDate(23, 9, "10:02"),
    actorId: "u-marina",
    action: "Convidou membro",
    target: "João Pereira · Atendente",
  },
  {
    id: "au-l-6",
    at: demoDate(12, 9, "10:20"),
    actorId: "u-marina",
    action: "Publicou conteúdo",
    target: "Política de trocas e devoluções · versão 3",
  },
];
